DotnetEF/DotnetEFCore/Controllers/AssetController.cs
using DotnetEFCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEFCore.Controllers
{
    public class AssetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AssetController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<AssetEntity> assets = _context.AssetEntities.ToList();
            return View(assets);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("Name, PurchaseYear, SerialNumber, Specification")] AssetEntity request)
        {
            // add to entity
            _context.AssetEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var entity = _context.AssetEntities.Find(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Update([Bind("Id, Name, PurchaseYear, SerialNumber, Specification")] AssetEntity request)
        {
            // update entity
            _context.AssetEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            var assetEntity = _context.AssetEntities.Find(id);
            if (assetEntity == null)
            {
                return Redirect("/Asset/GetAll");
            }
            // remove from entity
            _context.AssetEntities.Remove(assetEntity);
            // commit to database
            _context.SaveChanges();
            return Redirect("/Asset/GetAll");
        }
    }
}

DotnetEF/DotnetEFCore/Controllers/AuditController.cs
using DotnetEFCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEFCore.Controllers
{
    public class AuditController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AuditController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<AuditEntity> audits = _context.AuditEntities.ToList();
            return View(audits);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("PICName, AssetId, AntiVirus, OfficeLicense, WindowsLicense, AssetCondition")] AuditEntity request)
        {
            _context.AuditEntities.Add(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var entity = _context.AuditEntities.Find(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, PICName, AssetId, AntiVirus, OfficeLicense, WindowsLicense, AssetCondition")] AuditEntity request)
        {
            _context.AuditEntities.Update(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }
        [HttpGet]
        public IActionResult Delete(long? id)
        {
            var entity = _context.AuditEntities.Find(id);
            if (entity == null)
            {
                return Redirect("/Audit/GetAll");
            }
            _context.AuditEntities.Remove(entity);
            _context.SaveChanges();
            return Redirect("/Audit/GetAll");
        }
    }
}

DotnetEF/DotnetEFCore/Controllers/RequestController.cs
using DotnetEFCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEFCore.Controllers
{
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RequestController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<RequestEntity> requests = _context.RequestEntities.ToList();
            return View(requests);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("AssetId, PICName, SpecificationReq")] RequestEntity request)
        {
            _context.RequestEntities.Add(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var entity = _context.RequestEntities.Find(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, AssetId, PICName, SpecificationReq")] RequestEntity request)
        {
            _context.RequestEntities.Update(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            var entity = _context.RequestEntities.Find(id);
            if (entity == null)
            {
                return Redirect("/Request/GetAll");
            }
            _context.RequestEntities.Remove(entity);
            _context.SaveChanges();
            return Redirect("/Request/GetAll");
        }
    }
}

DotnetEF/DotnetEFCore/Controllers/TalentController.cs
using DotnetEFCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEFCore.Controllers
{
    public class TalentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TalentController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<TalentEntity> talents = _context.TalentEntities.ToList();
            return View(talents);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("Name, Email, Education, PlaceOfBirth, DateOfBirth")] TalentEntity request)
        {
            _context.TalentEntities.Add(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var entity = _context.TalentEntities.Find(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, Name, Email, Education, PlaceOfBirth, DateOfBirth")] TalentEntity request)
        {
            _context.TalentEntities.Update(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            var entity = _context.TalentEntities.Find(id);
            if (entity == null)
            {
                return Redirect("/Talent/GetAll");
            }
            _context.TalentEntities.Remove(entity);
            _context.SaveChanges();
            return Redirect("/Talent/GetAll");
        }
    }
}

DotnetEF/DotnetEFCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetEFCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotnetEFCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotnetEFCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Asset" asp-action="GetAll">Asset</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Talent" asp-action="GetAll">Talent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Request" asp-action="GetAll">Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Audit" asp-action="GetAll">Audit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="ReturnAsset" asp-action="GetAll">Return Asset</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2023 - DotnetEFCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>