DotnetEF/DotnetEFCore/Controllers/CategoryController.cs
using DotnetEFCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEFCore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<CategoryEntity> categories = _context.CategoryEntities.ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            CategoryEntity category = _context.CategoryEntities.Find(id);
            return View(category);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("CategoryCode, CategoryName, Description")] CategoryEntity request)
        {
            // add to entity
            _context.CategoryEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var entity = _context.CategoryEntities.Find(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id,CategoryCode, CategoryName, Description")] CategoryEntity request)
        {
            // update entity
            _context.CategoryEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var entity = _context.CategoryEntities.Find(id);
            if (entity == null)
            {
                return Redirect("/Category/GetAll");
            }
            // remove from entity
            _context.CategoryEntities.Remove(entity);
            // commit to database
            _context.SaveChanges();
            return Redirect("/Category/GetAll");
        }

        

    }
}

DotnetEF/DotnetEFCore/Views/Category/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DotnetEFCore.DataContext.CategoryEntity

@{
    ViewBag.Title = "Add New Category";
    Layout = "_Layout";
}

<h2>Add New Category</h2>
<form asp-controller="Category" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

DotnetEF/DotnetEFCore/Views/Category/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DotnetEFCore.DataContext.CategoryEntity

@{
    ViewBag.Title = "Detail of Category";
    Layout = "_Layout";
}

<h2>Detail Category</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Code</th>
        <td>@Model.CategoryCode</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
</table>

DotnetEF/DotnetEFCore/Views/Category/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DotnetEFCore.DataContext.CategoryEntity

@{
    ViewBag.Title = "Edit Category";
    Layout = "_Layout";
}

<h2>Edit Category</h2>
<form asp-controller="Category" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

DotnetEF/DotnetEFCore/Views/Category/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<DotnetEFCore.DataContext.CategoryEntity>

@{
    ViewBag.Title = "Categories";
    Layout = "_Layout";
}

<h2>Category Get All</h2>
<div class="pt-2 pb-2">
    <a asp-action="Add" class="btn btn-primary" role="button">Tambah Category</a>
</div>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Code</th>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.CategoryCode</td>
                <td>@item.CategoryName</td>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>