DotnetEF/DotnetEFCore/Controllers/ReturnAssetController.cs
using DotnetEFCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEFCore.Controllers
{
    public class ReturnAssetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReturnAssetController(ApplicationDbContext context) { _context = context; }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<ReturnAssetEntity> returnAssets = _context.ReturnAssetEntities.ToList();
            return View(returnAssets);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("AssetId, PICName, ReturnDate")] ReturnAssetEntity request)
        {
            request.ReturnDate = DateTime.Now;
            _context.ReturnAssetEntities.Add(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var entity = _context.ReturnAssetEntities.Find(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, AssetId, PICName, ReturnDate")] ReturnAssetEntity request)
        {
            _context.ReturnAssetEntities.Update(request);
            _context.SaveChanges();
            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            var entity = _context.ReturnAssetEntities.Find(id);
            if (entity == null)
            {
                return Redirect("/Request/GetAll");
            }
            _context.ReturnAssetEntities.Remove(entity);
            _context.SaveChanges();
            return Redirect("/Request/GetAll");
        }
    }
}

DotnetEF/DotnetEFCore/Views/ReturnAsset/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DotnetEFCore.DataContext.ReturnAssetEntity
@{
    ViewData["Title"] = "Return Asset Add Data";
}

<h2>Form Submit Return Asset</h2>
<form asp-controller="ReturnAsset" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="AssetId">Asset ID</label>
        <input asp-for="AssetId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PICName">PIC Name</label>
        <input asp-for="PICName" class="form-control" />
    </div>
    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

DotnetEF/DotnetEFCore/Views/ReturnAsset/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DotnetEFCore.DataContext.ReturnAssetEntity
@{
    ViewData["Title"] = "Return Asset Detail";
}

<h2>Return Asset Detail</h2>
<table class="table tab-content">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>Asset ID</th>
            <td>@Model.AssetId</td>
        </tr>
        <tr>
            <th>PIC Name</th>
            <td>@Model.PICName</td>
        </tr>
        <tr>
            <th>Return Date</th>
            <td>@Model.ReturnDate</td>
        </tr>

    </tbody>
</table>
<a asp-action="List" class="btn btn-sm btn-success">Back</a>

DotnetEF/DotnetEFCore/Views/ReturnAsset/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DotnetEFCore.DataContext.ReturnAssetEntity
@{
    ViewData["Title"] = "Return Asset - Edit Data";
}

<h2>Form Edit Return Asset</h2>
<form asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="AssetId">Asset ID</label>
        <input asp-for="AssetId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PICName">PIC Name</label>
        <input asp-for="PICName" class="form-control" />
    </div>
    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-sm btn-primary">Update</button>
        <button asp-action="List" class="btn btn-sm btn-success">Back</button>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotnetEF/DotnetEFCore/Views/ReturnAsset/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<DotnetEFCore.DataContext.ReturnAssetEntity>
@{
    ViewData["Title"] = "Return Asset List";
}

<h2>Return Asset List</h2>
<div class="pt-2 pb-2">
    <a asp-action="Add" class="btn btn-primary" role="button">Tambah Request</a>
</div>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>ID</th>
            <th>Asset ID</th>
            <th>PIC Name</th>
            <th>ReturnDate</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.AssetId</td>
                <td>@item.PICName</td>
                <td>@item.ReturnDate</td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>